baseURL = 'https://bastien.nizart.me/'
languageCode = 'fr'
title = 'Bastien Nizart'
contentDir = "content"
defaultContentLanguage = "fr"
enableRobotsTXT = true

[languages]
    [languages.fr]
        [languages.fr.params]
            name = 'Bastien Nizart'
            bio = 'Étudiant | Auto Entrepreneur Développeur Backend'
            socials = [
                { link = "https://github.com/bastien-nizart", icon = "fa-brands fa-github"},
                { link = "https://www.linkedin.com/in/bastien-nizart", icon = "fa-brands fa-linkedin"},
                { link = "mailto:bastien@nizart.me", icon = "fa-solid fa-envelope"},
                { link = "https://thumbmail.nizart.me/documents/cv-bastien-nizart.pdf", icon = "fa-solid fa-address-card"},
            ]
            tools = [
                { text = "Laravel, POO", icon = "fa-brands fa-php"},
                { text = "JavaFX, POO", icon = "fa-brands fa-java"},
                { text = "Flask, MathPlotLib", icon = "fa-brands fa-python"},
                { text = "Kotlin, Flutter", icon = "fa-solid fa-mobile-screen"},
                { text = "MySQL, PGSQL, SQL, SQLite", icon = "fa-solid fa-database"},
                { text = "Bootstrap, Flexbox", icon = "fa-brands fa-html5"},
                { text = "MacOS, Linux, Windows", icon = "fa-brands fa-linux"},
                { text = "Git, Bash, Apache", icon = "fa-solid fa-code-branch"},
            ]
            professionals = [
                { title = "Auto entrepreneur", date = "08/2022 - Aujourd'hui", location = "Admitech, Vermelles", responsibilities = [
                    "Création de logiciels fullstack pour différentes entreprises",
                    "Maintien et mise en place d'infrastructure cloud",
                    "Mise à jour de logiciel déjà existant"
                ]},
                { title = "Développeur Backend (stage)", date = "04/2023 - 06/2023", location = "Viously, Tourcoing", responsibilities = [
                    "Amélioration du workflow de développement",
                    "Ajout de fonctionnalités internes",
                ]},
                { title = "Développeur Backend", date = "01/2019 - 01/2023", location = "SSP, Vermelles", responsibilities = [
                    "Création d'une suite logicielle interne pour l'entreprise",
                    "Maintien et mise en place d'infrastructure cloud",
                    "Création de logiciels pour l'ensemble de l'entreprise (salarié, administration, finance...)",
                ]},
            ]
            studies = [
                { title = "License Informatique", date = "2023 - 2024", location = "Faculté des sciences Jean Perrin, Lens", description = "Préparation d'une L3 informatique à l'université Jean Perrin (Lens)" },
                { title = "BUT Informatique", date = "2021 - 2023", location = "IUT Informatique, Lens", description = "Obtention de ma deuxième année de BUT Informatique à l'IUT de Lens." },
                { title = "Baccalauréat Général", date = "2019 - 2021", location = "Lycée Marguerite Yourcenar, Beuvry", description = "Obtention du Baccalauréat Général option Maths - Physique - Maths expertes, mention bien." },
            ]
            associatives = [
                { title = "Mentor AFEV", date = "11/2022 - Aujourd'hui", location = "AFEV, Lens", description = "Accompagnement scolaire et social de deux enfants (primaire et collège) en difficultés." },
            ]